#PBS -N 02dpgp
#PBS -l ncpus=16
#PBS -l mem=60gb

### The purpose of this pbs is to be a Template for 02-DP_GP fine clustering in GeneShift workflow### 

cd ${PBS_O_WORKDIR}



source activate DPGP_env
BASEDIR=$(cat basedir.txt)
DP_GP_cluster.py -i ${BASEDIR}/02-DP_GP/Inputs/DTW-K1DPGP_input/*DTW-K1-Cluster1.txt -o ${BASEDIR}/02-DP_GP/DTW-K1DPGP_output/DTW-K1-Cluster1 -n 1000 --fast --true_times


